import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Menu from '@/components/client/menu';

import CategoriesMenu from '@/components/client/categoriesMenu';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Menu><CategoriesMenu/></Menu>
        {children}
     
      </body>
    </html>
  )
}
